/**
 * Common test utilities
 * Shared across all collections
 * Compatible with Postman and Newman
 */


/**
 * Parse JSON safely
 */

function parseJsonResponse() {

    try {

        return pm.response.json()

    } catch (e) {

        pm.test("Response body is valid JSON", function () {

            pm.expect.fail("Response body is not valid JSON")

        })

        return null

    }

}


/**
 * Get raw response text
 */

function responseText() {

    return pm.response.text()

}


/**
 * Flatten object to string
 */

function flatten(obj) {

    return JSON.stringify(obj)

}


/**
 * Basic HTTP validations
 */

function assertStatus200() {

    pm.test("HTTP status is 200", function () {

        pm.response.to.have.status(200)

    })

}


function assertCreated() {

    pm.test("HTTP status indicates resource creation", function () {

        pm.expect(pm.response.code).to.be.oneOf([200, 201])

    })

}


/**
 * Generic status validator
 */

function assertStatus(expected) {

    pm.test(`HTTP status is ${expected}`, function () {

        pm.expect(pm.response.code).to.equal(expected)

    })

}


/**
 * Validate response time
 */

function assertResponseTime(maxMs = 2000) {

    pm.test(`Response time < ${maxMs} ms`, function () {

        pm.expect(pm.response.responseTime).to.be.below(maxMs)

    })

}


/**
 * Validate JSON field exists
 */

function assertFieldExists(obj, field) {

    pm.test(`Field '${field}' exists`, function () {

        pm.expect(obj).to.not.be.null
        pm.expect(obj).to.have.property(field)

    })

}


/**
 * Validate value is not empty
 */

function assertNotEmpty(value, name) {

    pm.test(`${name} is not empty`, function () {

        pm.expect(value).to.not.be.undefined
        pm.expect(value).to.not.be.null
        pm.expect(value).to.not.equal("")

    })

}


/**
 * Validate string contains value
 */

function assertContains(text, value, message = "Value found in response") {

    pm.test(message, function () {

        pm.expect(text).to.include(value)

    })

}


/**
 * Validate JSON response is not empty
 */

function assertJsonNotEmpty(json) {

    pm.test("JSON response not empty", function () {

        pm.expect(json).to.not.be.null
        pm.expect(Object.keys(json).length).to.be.above(0)

    })

}


/**
 * Save variable into collection variables
 */

function saveCollectionVar(key, value) {

    if (value !== undefined && value !== null) {

        pm.collectionVariables.set(key, value)
        pm.environment.set(key, value)

    }

}


/**
 * Read variable from collection scope first, then environment scope.
 */

function getStoredVar(key) {

    return pm.collectionVariables.get(key) || pm.environment.get(key)

}


/**
 * Store access token generated by login requests
 */

function handleLoginToken(json) {

    if (!json) return false

    const requestName = pm.info.requestName || ""

    if (requestName === "Provider Login") {

        assertStatus200()
        assertFieldExists(json, "access_token")
        saveCollectionVar("provider_jwt", json.access_token)
        return true

    }

    if (requestName === "Consumer Login") {

        assertStatus200()
        assertFieldExists(json, "access_token")
        saveCollectionVar("consumer_jwt", json.access_token)
        return true

    }

    return false

}


/**
 * Extract ID from JSON response
 */

function extractId(json, field, variableName) {

    if (!json) return

    const value = json[field]

    pm.test(`Extract ${field}`, function () {

        pm.expect(value).to.not.be.undefined

    })

    saveCollectionVar(variableName, value)

}


/**
 * Extract @id field used by EDC
 */

function extractAtId(json, variableName) {

    if (!json) return

    const id = json["@id"]

    pm.test("Response contains @id", function () {

        pm.expect(id).to.not.be.undefined

    })

    saveCollectionVar(variableName, id)

}


/**
 * Validate negotiation state
 */

function assertNegotiationFinalized(json) {

    pm.test("Negotiation finalized", function () {

        pm.expect(json.state).to.equal("FINALIZED")

    })

}


/**
 * Validate transfer state
 */

function assertTransferCompleted(json) {

    pm.test("Transfer completed", function () {

        pm.expect(json.state).to.be.oneOf([
            "COMPLETED",
            "FINALIZED"
        ])

    })

}


/**
 * Validate response has no EDC error
 */

function assertNoEdcError(json) {

    pm.test("Response does not contain EDC error", function () {

        if (json && json.error) {

            pm.expect.fail("EDC returned error: " + json.error)

        }

    })

}


/**
 * Debug helpers
 */

function logResponse() {

    console.log("Status:", pm.response.code)
    console.log("Response:", pm.response.text())

}


/**
 * Log JSON response
 */

function logJson() {

    try {

        console.log("JSON:", pm.response.json())

    } catch (e) {

        console.log("Response not JSON")

    }

}
