apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.connector.name }}-config
  labels:
    validation-environment-adapter: edc
data:
  connector-configuration.properties: |
{{ tpl (.Files.Get "config/connector-configuration.properties.tpl") . | indent 4 }}
