# Optional: set these in CI only when Node.js is not available in PATH.
# sonar.nodejs.executable=/path/to/node
# sonar.typescript.node=/path/to/node
# Required metadata
sonar.sourceEncoding=UTF-8
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/environment.*
sonar.tests=src/app
sonar.test.inclusions=**/*.spec.ts

sonar.ts.tslint.configPath=tslint.json
sonar.ts.coverage.lcovReportPath=coverage/coverage.lcov
# if using local tslint then enable the line below
# sonar.ts.tslint.outputPath=reports/lint_issues.json
