/**
 * EDC REST API
 * EDC REST APIs - merged by OpenApiMerger
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Injectable, inject } from '@angular/core';
import { HttpClient } from '@angular/common/http';
import { Observable, from, lastValueFrom } from 'rxjs';
import { expandArray, PolicyDefinition, QuerySpec, EDC_CONTEXT, JSON_LD_DEFAULT_CONTEXT } from "@think-it-labs/edc-connector-client";
import { PolicyDefinitionInput } from '@think-it-labs/edc-connector-client';
import { environment } from '../../../environments/environment';
import { CONTEXTS } from '../utils/app.constants';
import { ConnectorContextService } from './connector-context.service';

// Policy models (simplified for now - can be extended later)
export interface PolicyDefinitionCreateDto {
  policyDefinitionId: string;
  expression: Record<string, unknown>;
}

export interface PolicyDefinitionDto {
  policyDefinitionId: string;
  policy: Record<string, unknown>;
}

@Injectable({
  providedIn: 'root'
})
export class PolicyService {
  private readonly http = inject(HttpClient);
  private readonly connectorContextService = inject(ConnectorContextService);

  private get baseUrl(): string {
    return `${this.connectorContextService.getManagementApiUrl()}${environment.runtime.service.policy.baseUrl}`;
  }

  private get complexBaseUrl(): string {
    return `${this.connectorContextService.getManagementApiUrl()}${environment.runtime.service.policy.complexBaseUrl}`;
  }

  /**
   * Creates a new policy definition
   * @param input
   */
  public createPolicy(input: PolicyDefinitionInput): Observable<Record<string, unknown>> {
    const body = {
      ...input,
      "@context": {
        "@vocab": EDC_CONTEXT,
        "odrl": CONTEXTS.odrl
      }
    }

    return from(lastValueFrom(this.http.post<PolicyDefinition>(
      `${this.baseUrl}`, body
    )));
  }

  /**
   * Creates a new complex policy definition
   * @param input
   */
  public createComplexPolicy(input: PolicyDefinitionCreateDto): Observable<Record<string, unknown>> {
    return from(lastValueFrom(this.http.post<Record<string, unknown>>(
      `${this.complexBaseUrl}`, input
    )));
  }

  /**
   * Removes a policy definition with the given ID if possible. Deleting a policy definition is only possible if that policy definition is not yet referenced by a contract definition, in which case an error is returned. DANGER ZONE: Note that deleting policy definitions can have unexpected results, do this at your own risk!
   * @param id
   */
  public deletePolicy(id: string): Observable<Record<string, unknown>> {
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling deletePolicy.');
    }
    return from(lastValueFrom(this.http.delete<PolicyDefinition>(
      `${this.baseUrl}${environment.runtime.service.policy.get}${id}`
    )));
  }

  /**
   * Gets a policy definition with the given ID
   * @param id
   */
  public getPolicy(id: string): Observable<Record<string, unknown>> {
    if (id === null || id === undefined) {
      throw new Error('Required parameter id was null or undefined when calling getPolicy.');
    }

    return from(lastValueFrom(this.http.get<PolicyDefinition>(
      `${this.baseUrl}${environment.runtime.service.policy.get}${id}`
    )));
  }

  /**
   * Returns all policy definitions according to a query
   * @param querySpec
   **/
  public queryAllPolicies(querySpec?: QuerySpec): Observable<PolicyDefinition[]> {
    let body;

    if (querySpec) {
      body = {
        ...querySpec,
        "@context": JSON_LD_DEFAULT_CONTEXT,
      }
    }

    return from(lastValueFrom(this.http.post<PolicyDefinition[]>(
      `${this.baseUrl}${environment.runtime.service.policy.getAll}`, body
    )).then(results => {
      return expandArray(results, () => new PolicyDefinition());
    }));
  }

  /**
   * Gets the total number of policies
   */
  public count(): Observable<number> {
    const querySpec: QuerySpec = {
      filterExpression: []
    }

    const body = {
      "@context": JSON_LD_DEFAULT_CONTEXT,
      ...querySpec
    };

    return from(lastValueFrom(this.http.post<number>(
      `${this.connectorContextService.getManagementApiUrl()}${environment.runtime.service.policy.count}`, body
    )));
  }

  /**
   * Returns all complex policy definitions according to a query
   * @param querySpec
   **/
  public queryAllComplexPolicies(querySpec?: QuerySpec): Observable<PolicyDefinitionDto[]> {
    let body;

    if (querySpec) {
      body = {
        ...querySpec,
        "@context": JSON_LD_DEFAULT_CONTEXT,
      }
    }

    return from(lastValueFrom(this.http.post<PolicyDefinitionDto[]>(
      `${this.complexBaseUrl}${environment.runtime.service.policy.getAll}`, body
    )).then(results => {
      return results;
    }));
  }
}
