{{- if and (not .Values.secrets.existingSecretName) (gt (len .Values.secrets.values) 0) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ai-model-hub.secretName" . }}
  labels:
    {{- include "ai-model-hub.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- range $k, $v := .Values.secrets.values }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
