apiVersion: v2
name: edc-connector
description: A Helm chart for deploying the PIONERA benchmark EDC connector in the Validation-Environment
type: application
version: 0.2.0
appVersion: "asset-filter-template"
