{{- if eq .Values.dataspace.environment "pro" }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.dataspace.name }}-portal-backend-cert
spec:
  secretName: {{ .Values.dataspace.name }}-ppb-tls-cert
  duration: 8760h
  renewBefore: 720h
  commonName: {{ .Values.dataspace.name }}-portal-backend
  dnsNames:
    - "*.{{ .Values.dataspace.name }}-portal-backend"
    - "*.{{ .Values.dataspace.name }}.svc"
    - "*.ds.dataspaceunit-project.eu"
    - {{ .Values.ingress.backend.hostname }}
    - {{ .Values.dataspace.name }}-portal-backend
    - portal-backend
  ipAddresses:
    - 127.0.0.1
  issuerRef:
    name: elastic-selfsigned-cluster-issuer
    kind: ClusterIssuer
{{- end }}
