#!/usr/bin/env python3
"""Read-only audit for the AI Model Hub use-case catalog.

The vm-distributed validation environment should expose the AI Model Hub
use-case models in split mode:

* provider/city publishes its owned model assets;
* consumer/company publishes its owned model assets and datasets;
* only JS_DAIMO_Model and JS_DAIMO_Dataset vocabularies are expected.

This script does not delete or mutate anything. It authenticates with the
connector credentials already generated by the deployment and reports missing,
duplicated, wrong-owner, and legacy sentiment/test artifacts.
"""
from __future__ import annotations

import argparse
import json
import re
import ssl
import sys
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass
from typing import Any


DEFAULT_TOKEN_URL = "https://org1.pionera.oeg.fi.upm.es/auth/realms/pionera/protocol/openid-connect/token"
DEFAULT_CREDENTIALS_DIR = "deployers/inesdata/deployments/DEV/vm-distributed/pionera/connectors"
DEFAULT_MODEL_SERVER_URL = "https://org1.pionera.oeg.fi.upm.es/model-server"
DEFAULT_CONNECTOR_HOSTS = {
    "conn-org2-pionera": "org2.pionera.oeg.fi.upm.es",
    "conn-org3-pionera": "org3.pionera.oeg.fi.upm.es",
}
DEFAULT_CONNECTOR_TAGS = {
    "conn-org2-pionera": "city",
    "conn-org3-pionera": "company",
}
KEEP_VOCABULARIES = {"JS_DAIMO_Model", "JS_DAIMO_Dataset"}
KEEP_DATASET_ASSETS = {
    "company-mobility-segments-test",
    "company-flares-5w1h-test",
    "company-flares-reliability-test",
}
INPUT_SCHEMA_KEYS = {
    "daimo:inputSchema",
    "https://w3id.org/pionera/daimo#inputSchema",
    "inputSchema",
}
USE_CASE_MODEL_SLUGS = [
    "flares-5w1h-albert",
    "flares-reliability-albert",
    "flares-5w1h-bert",
    "flares-reliability-bert",
    "flares-5w1h-distilbert",
    "flares-reliability-distilbert",
    "mobility-lightgbm-actual-travel-time",
    "mobility-randomforest-actual-travel-time",
    "mobility-catboost-actual-travel-time",
    "mobility-lightgbm-delay",
    "mobility-randomforest-delay",
    "mobility-catboost-delay",
    "mobility-lightgbm-previous-delay",
    "mobility-randomforest-previous-delay",
    "mobility-catboost-previous-delay",
]
FLARES_METRIC_MODEL_SLUGS = [
    "flares-5w1h-albert-metrics",
    "flares-reliability-albert-metrics",
    "flares-5w1h-bert-metrics",
    "flares-reliability-bert-metrics",
    "flares-5w1h-distilbert-metrics",
    "flares-reliability-distilbert-metrics",
]
CITY_MODEL_SLUGS = {
    "flares-5w1h-albert",
    "flares-reliability-albert",
    "flares-5w1h-distilbert",
    "flares-reliability-distilbert",
    "mobility-lightgbm-actual-travel-time",
    "mobility-randomforest-actual-travel-time",
    "flares-5w1h-albert-metrics",
    "flares-reliability-albert-metrics",
    "flares-5w1h-distilbert-metrics",
    "flares-reliability-distilbert-metrics",
}
COMPANY_MODEL_SLUGS = {
    "flares-5w1h-bert",
    "flares-reliability-bert",
    "mobility-catboost-actual-travel-time",
    "mobility-lightgbm-delay",
    "mobility-randomforest-delay",
    "mobility-catboost-delay",
    "mobility-lightgbm-previous-delay",
    "mobility-randomforest-previous-delay",
    "mobility-catboost-previous-delay",
    "flares-5w1h-bert-metrics",
    "flares-reliability-bert-metrics",
}
LEGACY_TEXT_RE = re.compile(
    r"(sentiment|twitter|ecommerce|qa-ui-|asset-e2e-|contract-ui-|policy-ui-|test-)",
    re.IGNORECASE,
)
EDC_CTX = {"@context": {"@vocab": "https://w3id.org/edc/v0.0.1/ns/"}}


@dataclass(frozen=True)
class Connector:
    name: str
    host: str
    tag: str


def ssl_context() -> ssl.SSLContext:
    ctx = ssl.create_default_context()
    ctx.check_hostname = False
    ctx.verify_mode = ssl.CERT_NONE
    return ctx


def http_json(
    method: str,
    url: str,
    *,
    token: str | None = None,
    payload: Any | None = None,
    timeout: int = 90,
    ctx: ssl.SSLContext,
) -> Any:
    data = None
    headers: dict[str, str] = {}
    if payload is not None:
        data = json.dumps(payload).encode("utf-8")
        headers["Content-Type"] = "application/json"
    if token:
        headers["Authorization"] = f"Bearer {token}"
    req = urllib.request.Request(url, data=data, headers=headers, method=method)
    with urllib.request.urlopen(req, timeout=timeout, context=ctx) as response:
        raw = response.read().decode("utf-8", errors="replace")
    return json.loads(raw) if raw.strip() else None


def token_for_connector(credentials_dir: str, connector: str, token_url: str, ctx: ssl.SSLContext) -> str:
    path = f"{credentials_dir.rstrip('/')}/{connector}/credentials.json"
    with open(path, encoding="utf-8") as handle:
        credentials = json.load(handle)
    user = credentials["connector_user"]["user"]
    password = credentials["connector_user"]["passwd"]
    data = urllib.parse.urlencode(
        {
            "grant_type": "password",
            "client_id": "dataspace-users",
            "username": user,
            "password": password,
        }
    ).encode("utf-8")
    req = urllib.request.Request(token_url, data=data, method="POST")
    with urllib.request.urlopen(req, timeout=30, context=ctx) as response:
        payload = json.load(response)
    return str(payload["access_token"])


def query_management(host: str, token: str, kind: str, ctx: ssl.SSLContext) -> list[dict[str, Any]]:
    url = f"https://{host}/management/v3/{kind}/request"
    payload = {**EDC_CTX, "@type": "QuerySpec", "limit": 10000}
    result = http_json("POST", url, token=token, payload=payload, timeout=120, ctx=ctx)
    return result if isinstance(result, list) else []


def query_management_optional(host: str, token: str, kind: str, ctx: ssl.SSLContext) -> list[dict[str, Any]]:
    try:
        return query_management(host, token, kind, ctx)
    except urllib.error.HTTPError as exc:
        if exc.code == 404:
            return []
        raise


def query_vocabularies(host: str, token: str, ctx: ssl.SSLContext) -> list[dict[str, Any]]:
    payload = {**EDC_CTX, "@type": "QuerySpec", "limit": 10000}
    for base in ("vocabularies", "v3/vocabularies"):
        url = f"https://{host}/management/{base}/request"
        try:
            result = http_json("POST", url, token=token, payload=payload, timeout=120, ctx=ctx)
            return result if isinstance(result, list) else []
        except urllib.error.HTTPError as exc:
            if exc.code != 404:
                raise
    return []


def slugify(value: str) -> str:
    normalized = re.sub(r"[^A-Za-z0-9]+", "-", str(value).strip().lower())
    return normalized.strip("-") or "model"


def discover_model_slugs(model_server_url: str, ctx: ssl.SSLContext) -> dict[str, str]:
    url = f"{model_server_url.rstrip('/')}/models"
    payload = http_json("GET", url, timeout=60, ctx=ctx)
    if not isinstance(payload, dict):
        raise RuntimeError(f"Model discovery did not return an object: {url}")

    slugs: dict[str, str] = {}
    for model_name in payload.get("flares") or []:
        slugs[f"flares-{slugify(str(model_name))}"] = str(model_name)
    for model_name in payload.get("mobility") or []:
        slugs[f"mobility-{slugify(str(model_name))}"] = str(model_name)
    return slugs


def expected_model_slugs() -> dict[str, str]:
    return {slug: slug for slug in [*USE_CASE_MODEL_SLUGS, *FLARES_METRIC_MODEL_SLUGS]}


def owner_for_slug(slug: str) -> str:
    if slug in CITY_MODEL_SLUGS:
        return "city"
    if slug in COMPANY_MODEL_SLUGS:
        return "company"
    return "both"


def identifier(item: dict[str, Any]) -> str:
    return str(item.get("@id") or item.get("id") or "")


def cdef_asset_id(contract_definition: dict[str, Any]) -> str:
    selector = (
        contract_definition.get("assetsSelector")
        or contract_definition.get("https://w3id.org/edc/v0.0.1/ns/assetsSelector")
        or []
    )
    if isinstance(selector, dict):
        selector = [selector]
    for criterion in selector:
        if not isinstance(criterion, dict):
            continue
        value = (
            criterion.get("operandRight")
            or criterion.get("https://w3id.org/edc/v0.0.1/ns/operandRight")
        )
        if value:
            return str(value)
    return ""


def agreement_asset_id(contract_agreement: dict[str, Any]) -> str:
    for key in (
        "assetId",
        "https://w3id.org/edc/v0.0.1/ns/assetId",
        "edc:assetId",
    ):
        value = contract_agreement.get(key)
        if value:
            return str(value)
    return ""


def searchable_text(item: dict[str, Any]) -> str:
    try:
        return json.dumps(item, ensure_ascii=False, sort_keys=True)
    except TypeError:
        return str(item)


def non_empty_metadata_value(value: Any) -> bool:
    return value not in (None, "", [], {})


def contains_any_key(value: Any, keys: set[str]) -> bool:
    if isinstance(value, dict):
        for key, child in value.items():
            if key in keys and non_empty_metadata_value(child):
                return True
            if contains_any_key(child, keys):
                return True
    elif isinstance(value, list):
        return any(contains_any_key(item, keys) for item in value)
    return False


def has_input_schema(asset: dict[str, Any]) -> bool:
    return contains_any_key(asset, INPUT_SCHEMA_KEYS)


def expected_asset_ids(slugs: dict[str, str]) -> dict[str, list[str]]:
    expected: dict[str, list[str]] = {"city": [], "company": []}
    for slug in sorted(slugs):
        owner = owner_for_slug(slug)
        if owner == "both":
            expected["city"].append(f"city-{slug}")
            expected["company"].append(f"company-{slug}")
        else:
            expected[owner].append(f"{owner}-{slug}")
    return expected


def expected_dataset_asset_ids() -> dict[str, list[str]]:
    return {
        "city": [],
        "company": sorted(KEEP_DATASET_ASSETS),
    }


def vocabulary_duplicates(vocabularies: list[dict[str, Any]]) -> list[str]:
    counts: dict[str, int] = {}
    for vocabulary in vocabularies:
        value = identifier(vocabulary)
        if value:
            counts[value] = counts.get(value, 0) + 1
    return sorted(value for value, count in counts.items() if count > 1)


def parse_connectors(raw_hosts: str, raw_tags: str) -> list[Connector]:
    hosts = dict(DEFAULT_CONNECTOR_HOSTS)
    if raw_hosts:
        hosts.clear()
        for entry in raw_hosts.split(","):
            if not entry.strip():
                continue
            name, sep, host = entry.partition("=")
            if not sep:
                raise ValueError(f"Invalid connector host entry: {entry}")
            hosts[name.strip()] = host.strip()

    tags = dict(DEFAULT_CONNECTOR_TAGS)
    if raw_tags:
        tags.clear()
        for entry in raw_tags.split(","):
            if not entry.strip():
                continue
            name, sep, tag = entry.partition("=")
            if not sep:
                raise ValueError(f"Invalid connector tag entry: {entry}")
            tags[name.strip()] = tag.strip()

    return [Connector(name=name, host=host, tag=tags.get(name, "")) for name, host in hosts.items()]


def audit(args: argparse.Namespace) -> dict[str, Any]:
    ctx = ssl_context()
    connectors = parse_connectors(args.connector_hosts, args.connector_tags)
    discovered_slugs = discover_model_slugs(args.model_server_url, ctx)
    slugs = expected_model_slugs()
    expected = expected_asset_ids(slugs)
    expected_datasets = expected_dataset_asset_ids()
    report: dict[str, Any] = {
        "model_server_url": args.model_server_url.rstrip("/"),
        "model_count": len(slugs),
        "dataset_count": len(KEEP_DATASET_ASSETS),
        "discovered_prediction_model_count": len(discovered_slugs),
        "models": [{"slug": slug, "name": name, "owner": owner_for_slug(slug)} for slug, name in sorted(slugs.items())],
        "datasets": sorted(KEEP_DATASET_ASSETS),
        "connectors": {},
        "summary": {
            "missing_expected_assets": 0,
            "missing_expected_contracts": 0,
            "missing_expected_datasets": 0,
            "missing_expected_dataset_contracts": 0,
            "missing_input_schema_model_assets": 0,
            "wrong_owner_model_assets": 0,
            "legacy_artifacts": 0,
            "legacy_model_assets_missing_input_schema": 0,
            "unexpected_vocabularies": 0,
            "duplicated_vocabularies": 0,
        },
    }

    slug_set = set(slugs)
    for connector in connectors:
        token = token_for_connector(args.credentials_dir, connector.name, args.token_url, ctx)
        assets = query_management(connector.host, token, "assets", ctx)
        contracts = query_management(connector.host, token, "contractdefinitions", ctx)
        policies = query_management(connector.host, token, "policydefinitions", ctx)
        agreements = query_management_optional(connector.host, token, "contractagreements", ctx)
        vocabularies = query_vocabularies(connector.host, token, ctx)

        asset_ids = {identifier(item) for item in assets}
        contract_asset_ids = {cdef_asset_id(item) for item in contracts}
        agreement_asset_ids = {agreement_asset_id(item) for item in agreements if agreement_asset_id(item)}
        expected_ids = expected.get(connector.tag, [])
        missing_assets = [asset_id for asset_id in expected_ids if asset_id not in asset_ids]
        missing_contracts = [asset_id for asset_id in expected_ids if asset_id not in contract_asset_ids]
        expected_dataset_ids = expected_datasets.get(connector.tag, [])
        missing_datasets = [asset_id for asset_id in expected_dataset_ids if asset_id not in asset_ids]
        missing_dataset_contracts = [
            asset_id for asset_id in expected_dataset_ids if asset_id not in contract_asset_ids
        ]
        missing_input_schema_model_assets = sorted(
            identifier(item)
            for item in assets
            if identifier(item) in expected_ids and not has_input_schema(item)
        )
        dataset_assets = sorted(asset_id for asset_id in asset_ids if asset_id in KEEP_DATASET_ASSETS)

        wrong_owner_assets = []
        duplicate_slug_assets: dict[str, list[str]] = {}
        for asset_id in sorted(asset_ids):
            for prefix in ("city-", "company-"):
                if not asset_id.startswith(prefix):
                    continue
                slug = asset_id[len(prefix) :]
                if slug not in slug_set:
                    continue
                duplicate_slug_assets.setdefault(slug, []).append(asset_id)
                owner = owner_for_slug(slug)
                tag = prefix[:-1]
                if owner != "both" and owner != tag:
                    wrong_owner_assets.append(asset_id)

        legacy_assets = sorted(
            item_id
            for item in assets
            for item_id in [identifier(item)]
            if item_id not in KEEP_DATASET_ASSETS
            and (LEGACY_TEXT_RE.search(item_id) or LEGACY_TEXT_RE.search(searchable_text(item)))
        )
        legacy_model_assets_missing_input_schema = sorted(
            identifier(item)
            for item in assets
            if identifier(item) in legacy_assets and not has_input_schema(item)
        )
        legacy_contracts = sorted(
            identifier(item)
            for item in contracts
            if LEGACY_TEXT_RE.search(identifier(item)) or LEGACY_TEXT_RE.search(searchable_text(item))
        )
        legacy_policies = sorted(
            identifier(item)
            for item in policies
            if LEGACY_TEXT_RE.search(identifier(item)) or LEGACY_TEXT_RE.search(searchable_text(item))
        )
        unexpected_vocabularies = sorted(
            identifier(item)
            for item in vocabularies
            if identifier(item) and identifier(item) not in KEEP_VOCABULARIES
        )
        duplicated_vocabularies = vocabulary_duplicates(vocabularies)
        referenced_stale_assets = sorted(
            item for item in set(legacy_assets).union(wrong_owner_assets) if item in agreement_asset_ids
        )

        report["connectors"][connector.name] = {
            "host": connector.host,
            "tag": connector.tag,
            "asset_count": len(assets),
            "contract_definition_count": len(contracts),
            "policy_definition_count": len(policies),
            "contract_agreement_count": len(agreements),
            "vocabulary_count": len(vocabularies),
            "expected_model_asset_count": len(expected_ids),
            "expected_dataset_asset_count": len(expected_dataset_ids),
            "missing_expected_assets": missing_assets,
            "missing_expected_contracts": missing_contracts,
            "missing_expected_datasets": missing_datasets,
            "missing_expected_dataset_contracts": missing_dataset_contracts,
            "missing_input_schema_model_assets": missing_input_schema_model_assets,
            "dataset_assets": dataset_assets,
            "wrong_owner_model_assets": sorted(wrong_owner_assets),
            "model_slug_assets": dict(sorted(duplicate_slug_assets.items())),
            "legacy_assets": legacy_assets,
            "legacy_model_assets_missing_input_schema": legacy_model_assets_missing_input_schema,
            "legacy_contract_definitions": legacy_contracts,
            "legacy_policy_definitions": legacy_policies,
            "vocabularies": sorted(identifier(item) for item in vocabularies if identifier(item)),
            "unexpected_vocabularies": unexpected_vocabularies,
            "duplicated_vocabularies": duplicated_vocabularies,
            "referenced_stale_assets": referenced_stale_assets,
        }
        report["summary"]["missing_expected_assets"] += len(missing_assets)
        report["summary"]["missing_expected_contracts"] += len(missing_contracts)
        report["summary"]["missing_expected_datasets"] += len(missing_datasets)
        report["summary"]["missing_expected_dataset_contracts"] += len(missing_dataset_contracts)
        report["summary"]["missing_input_schema_model_assets"] += len(missing_input_schema_model_assets)
        report["summary"]["wrong_owner_model_assets"] += len(wrong_owner_assets)
        report["summary"]["legacy_artifacts"] += len(legacy_assets) + len(legacy_contracts) + len(legacy_policies)
        report["summary"]["legacy_model_assets_missing_input_schema"] += len(legacy_model_assets_missing_input_schema)
        report["summary"]["unexpected_vocabularies"] += len(unexpected_vocabularies)
        report["summary"]["duplicated_vocabularies"] += len(duplicated_vocabularies)

    return report


def print_report(report: dict[str, Any], *, verbose: bool) -> None:
    print(f"Model server: {report['model_server_url']}")
    print(f"Expected model assets: {report['model_count']}")
    print(f"Expected dataset assets: {report['dataset_count']}")
    print(f"Discovered prediction models: {report['discovered_prediction_model_count']}")
    owners: dict[str, int] = {}
    for model in report["models"]:
        owners[model["owner"]] = owners.get(model["owner"], 0) + 1
    print("Owner split: " + ", ".join(f"{key}={value}" for key, value in sorted(owners.items())))
    print("Summary: " + json.dumps(report["summary"], sort_keys=True))
    for connector_name, connector_report in report["connectors"].items():
        print()
        print(f"{connector_name} ({connector_report['tag']}):")
        print(
            "  assets={asset_count}, contracts={contract_definition_count}, policies={policy_definition_count}, "
            "agreements={contract_agreement_count}, vocabularies={vocabulary_count}, "
            "expected_models={expected_model_asset_count}, expected_datasets={expected_dataset_asset_count}".format(
                **connector_report
            )
        )
        for key in (
            "missing_expected_assets",
            "missing_expected_contracts",
            "missing_expected_datasets",
            "missing_expected_dataset_contracts",
            "missing_input_schema_model_assets",
            "wrong_owner_model_assets",
            "legacy_assets",
            "legacy_model_assets_missing_input_schema",
            "legacy_contract_definitions",
            "legacy_policy_definitions",
            "unexpected_vocabularies",
            "duplicated_vocabularies",
            "referenced_stale_assets",
        ):
            values = connector_report[key]
            print(f"  {key}: {len(values)}")
            if verbose and values:
                for value in values:
                    print(f"    - {value}")
        if verbose:
            print("  dataset_assets:")
            for value in connector_report["dataset_assets"]:
                print(f"    - {value}")
            print("  vocabularies:")
            for value in connector_report["vocabularies"]:
                print(f"    - {value}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--credentials-dir", default=DEFAULT_CREDENTIALS_DIR)
    parser.add_argument("--token-url", default=DEFAULT_TOKEN_URL)
    parser.add_argument("--model-server-url", default=DEFAULT_MODEL_SERVER_URL)
    parser.add_argument(
        "--connector-hosts",
        default="",
        help="Comma list like conn-a=host-a,conn-b=host-b. Defaults to vm-distributed PIONERA.",
    )
    parser.add_argument(
        "--connector-tags",
        default="",
        help="Comma list like conn-a=city,conn-b=company. Defaults to org2=city,org3=company.",
    )
    parser.add_argument("--json", action="store_true", help="print full JSON report")
    parser.add_argument("--verbose", action="store_true", help="print identifier lists")
    args = parser.parse_args()

    try:
        report = audit(args)
    except Exception as exc:  # noqa: BLE001
        print(f"Audit failed: {exc}", file=sys.stderr)
        return 2

    if args.json:
        print(json.dumps(report, indent=2, sort_keys=True))
    else:
        print_report(report, verbose=args.verbose)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
