/**
 * EDC REST API
 * EDC REST APIs - merged by OpenApiMerger
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
/* tslint:disable:no-unused-variable member-ordering */

import { Injectable } from '@angular/core';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { Observable, from, lastValueFrom, throwError } from 'rxjs';
import { TransferProcessInput, QuerySpec } from "../models/edc-connector-entities";
import { environment } from 'src/environments/environment';
import { expand, expandArray, IdResponse, JSON_LD_DEFAULT_CONTEXT, TransferProcess, TransferProcessState } from '@think-it-labs/edc-connector-client';

export interface EndpointDataAddress {
  [key: string]: any;
}

@Injectable({
  providedIn: 'root'
})
export class TransferProcessService {
  private readonly BASE_URL = `${environment.runtime.managementApiUrl}${environment.runtime.service.transferProcess.baseUrl}`;
  private readonly INESDATA_BASE_URL = `${environment.runtime.managementApiUrl}${environment.runtime.service.transferProcess.inesdataBaseUrl}`;

  constructor(private http: HttpClient) {
  }

  /**
   * Requests aborting the transfer process. Due to the asynchronous nature of transfers, a successful response only indicates that the request was successfully received. Clients must poll the /{id}/state endpoint to track the state.
   * @param id
   */
  public cancelTransferProcess(id: string): Observable<any> {
    let body = {
      reason: "Call by DataDashboard.",
      "@id": id,
      "@context": JSON_LD_DEFAULT_CONTEXT,
    }

    return from(lastValueFrom(this.http.post<any>(
      `${this.BASE_URL}${environment.runtime.service.transferProcess.get}${id}${environment.runtime.service.transferProcess.terminate}`, body
    )));
  }

  /**
   * Requests the deprovisioning of resources associated with a transfer process. Due to the asynchronous nature of transfers, a successful response only indicates that the request was successfully received. This may take a long time, so clients must poll the /{id}/state endpoint to track the state.
   * @param id
   */
  public deprovisionTransferProcess(id: string): Observable<any> {
    let body = {
      "@id": id,
      "@context": JSON_LD_DEFAULT_CONTEXT,
    }

    return from(lastValueFrom(this.http.post<any>(
      `${this.BASE_URL}${environment.runtime.service.transferProcess.get}${id}${environment.runtime.service.transferProcess.deprovision}`, body
    )));
  }

  /**
   * Gets a transfer process with the given ID
   * @param id
   */
  public getTransferProcess(id: string): Observable<any> {
    return from(lastValueFrom(this.http.get<TransferProcess>(
      `${this.BASE_URL}${environment.runtime.service.transferProcess.get}${id}`
    )).then(result => {
      return expand(result, () => new TransferProcess());
    }));
  }

  /**
   * Gets the state of a transfer process with the given ID
   * @param id
   */
  public getTransferProcessState(id: string): Observable<any> {
    return from(lastValueFrom(this.http.get<TransferProcessState>(
      `${this.BASE_URL}${environment.runtime.service.transferProcess.get}${id}${environment.runtime.service.transferProcess.state}`
    )).then(result => {
      return expand(result, () => new TransferProcessState());
    }));
  }

  /**
   * Initiates a data transfer with the given parameters. Please note that successfully invoking this endpoint only means that the transfer was initiated. Clients must poll the /{id}/state endpoint to track the state
   * @param transferRequestInput
   */
  public initiateTransfer(transferRequestInput: TransferProcessInput): Observable<any> {
    let body = {
      protocol: "dataspace-protocol-http",
      "@context": JSON_LD_DEFAULT_CONTEXT,
      ...transferRequestInput
    }

    return from(lastValueFrom(this.http.post<any>(
      `${this.BASE_URL}`, body
    )).then(result => {
      return expand(result, () => new IdResponse());
    }));
  }


  /**
   * Initiates a data transfer with the given parameters. Please note that successfully invoking this endpoint only means that the transfer was initiated. Clients must poll the /{id}/state endpoint to track the state
   * @param transferRequestInput
   */
  public initiateInesdataTransfer(transferRequestInput: TransferProcessInput): Observable<any> {
    let body = {
      protocol: "dataspace-protocol-http",
      "@context": JSON_LD_DEFAULT_CONTEXT,
      ...transferRequestInput
    }

    return from(lastValueFrom(this.http.post<any>(
      `${this.INESDATA_BASE_URL}`, body
    )).then(result => {
      return expand(result, () => new IdResponse());
    }));
  }

  public getTransferDataAddress(transferProcessId: string): Observable<EndpointDataAddress> {
    return this.http.get<EndpointDataAddress>(
      `${environment.runtime.managementApiUrl}/v3/edrs/${encodeURIComponent(transferProcessId)}/dataaddress`
    );
  }

  public downloadEndpointData(dataAddress: EndpointDataAddress): Observable<Blob> {
    const endpoint = this.firstText(
      dataAddress?.endpoint,
      dataAddress?.['edc:endpoint'],
      dataAddress?.['https://w3id.org/edc/v0.0.1/ns/endpoint'],
      dataAddress?.endpointUrl,
      dataAddress?.['edc:endpointUrl']
    );
    const authorization = this.firstText(
      dataAddress?.authorization,
      dataAddress?.['edc:authorization'],
      dataAddress?.['https://w3id.org/edc/v0.0.1/ns/authorization'],
      dataAddress?.authCode,
      dataAddress?.['edc:authCode']
    );
    const authHeader = this.firstText(
      dataAddress?.authHeader,
      dataAddress?.['edc:authHeader'],
      dataAddress?.['https://w3id.org/edc/v0.0.1/ns/authHeader'],
      dataAddress?.authKey,
      dataAddress?.['edc:authKey']
    ) || 'Authorization';

    if (!endpoint) {
      return throwError(() => new Error('Transfer EDR does not include a download endpoint.'));
    }

    let headers = new HttpHeaders({ Accept: 'application/octet-stream' });
    if (authorization) {
      headers = headers.set(authHeader, authorization);
    }

    return this.http.get(endpoint, { headers, responseType: 'blob' });
  }

  /**
   * Returns all transfer process according to a query
   * @param querySpec
   */
  public queryAllTransferProcesses(querySpec?: QuerySpec): Observable<any> {
    let body =
      querySpec === undefined || querySpec === null || Object.keys(querySpec).length === 0
        ? null
        : {
          ...querySpec,
          "@context": JSON_LD_DEFAULT_CONTEXT,
        }

    return from(lastValueFrom(this.http.post<TransferProcess[]>(
      `${this.BASE_URL}${environment.runtime.service.transferProcess.getAll}`, body
    )).then(results => {
      if (!results || !Array.isArray(results)) {
        return [];
      }
      return expandArray(results, () => new TransferProcess());
    }));
  }


  /**
  * Gets the total number of transfers
  */
  public count(): Observable<number> {
    const querySpec: QuerySpec = {
      filterExpression: []
    }

    const body = {
      "@context": JSON_LD_DEFAULT_CONTEXT,
      ...querySpec
    };

    return from(lastValueFrom(this.http.post<number>(
      `${environment.runtime.managementApiUrl}${environment.runtime.service.transferProcess.count}`, body
    )));
  }

  private firstText(...values: unknown[]): string {
    for (const value of values) {
      const resolved = this.resolveTextValue(value);
      if (resolved) {
        return resolved;
      }
    }
    return '';
  }

  private resolveTextValue(value: unknown): string {
    if (value === undefined || value === null) {
      return '';
    }

    if (Array.isArray(value)) {
      for (const item of value) {
        const resolved = this.resolveTextValue(item);
        if (resolved) {
          return resolved;
        }
      }
      return '';
    }

    if (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean') {
      return `${value}`.trim();
    }

    if (typeof value !== 'object') {
      return '';
    }

    const record = value as Record<string, unknown>;
    if (record['@value'] !== undefined) {
      return this.resolveTextValue(record['@value']);
    }

    if (record['@id'] !== undefined && Object.keys(record).length === 1) {
      return this.resolveTextValue(record['@id']);
    }

    for (const nestedValue of Object.values(record)) {
      const resolved = this.resolveTextValue(nestedValue);
      if (resolved) {
        return resolved;
      }
    }

    return '';
  }
}
