"""Common contracts and helpers for deployer-based orchestration."""

from .components import (
    COMPONENT_CONTRACTS,
    ComponentContract,
    build_component_preview,
    component_validation_groups,
    component_values_file_candidates,
    components_for_adapter,
    configured_component_host,
    configured_optional_components,
    get_component_contract,
    infer_component_hostname,
    normalize_component_key,
    resolve_component_release_name,
    strip_url_scheme,
    summarize_components_for_adapter,
)
from .config_loader import (
    apply_pionera_environment_overrides,
    detect_topology_key_migration_warnings,
    iter_dataspace_slots,
    load_deployer_config,
    load_layered_deployer_config,
    resolve_deployer_config_layer_paths,
    topology_overlay_config_path,
)
from .cluster_runtime import (
    K3S_CLUSTER_TYPE,
    MINIKUBE_CLUSTER_TYPE,
    SUPPORTED_CLUSTER_TYPES,
    build_cluster_runtime,
    normalize_cluster_type,
)
from .contracts import DeploymentContext, NamespaceRoles, TopologyProfile, ValidationProfile
from .hosts_manager import (
    HostBlock,
    HostEntry,
    apply_managed_blocks,
    blocks_as_dict,
    build_context_host_blocks,
    detect_legacy_external_hostnames,
    hostnames_by_level,
    merge_missing_managed_blocks,
    parse_hostnames,
    remove_managed_blocks,
    render_managed_block,
    upsert_managed_block,
    upsert_managed_blocks,
)
from .namespaces import (
    COMPACT_NAMESPACE_PROFILE,
    ROLE_ALIGNED_NAMESPACE_PROFILE,
    SUPPORTED_NAMESPACE_PROFILES,
    normalize_namespace_profile,
    resolve_namespace_profile_plan,
)
from .orchestrator import DeployerOrchestrator
from .topology import SUPPORTED_TOPOLOGIES, build_topology_profile, normalize_topology

__all__ = [
    "COMPONENT_CONTRACTS",
    "ComponentContract",
    "build_component_preview",
    "DeploymentContext",
    "DeployerOrchestrator",
    "HostBlock",
    "HostEntry",
    "NamespaceRoles",
    "COMPACT_NAMESPACE_PROFILE",
    "ROLE_ALIGNED_NAMESPACE_PROFILE",
    "SUPPORTED_CLUSTER_TYPES",
    "SUPPORTED_NAMESPACE_PROFILES",
    "SUPPORTED_TOPOLOGIES",
    "TopologyProfile",
    "ValidationProfile",
    "apply_managed_blocks",
    "blocks_as_dict",
    "build_cluster_runtime",
    "build_context_host_blocks",
    "build_topology_profile",
    "component_validation_groups",
    "component_values_file_candidates",
    "components_for_adapter",
    "configured_component_host",
    "configured_optional_components",
    "detect_topology_key_migration_warnings",
    "detect_legacy_external_hostnames",
    "get_component_contract",
    "hostnames_by_level",
    "infer_component_hostname",
    "iter_dataspace_slots",
    "K3S_CLUSTER_TYPE",
    "load_deployer_config",
    "apply_pionera_environment_overrides",
    "load_layered_deployer_config",
    "resolve_deployer_config_layer_paths",
    "merge_missing_managed_blocks",
    "MINIKUBE_CLUSTER_TYPE",
    "normalize_namespace_profile",
    "normalize_component_key",
    "normalize_cluster_type",
    "normalize_topology",
    "parse_hostnames",
    "remove_managed_blocks",
    "render_managed_block",
    "resolve_namespace_profile_plan",
    "resolve_component_release_name",
    "strip_url_scheme",
    "summarize_components_for_adapter",
    "topology_overlay_config_path",
    "upsert_managed_block",
    "upsert_managed_blocks",
]
