model.observer.journal.enabled=true
model.observer.journal.baseurl=http://localhost:1337
model.observer.journal.events.path=/api/model-observer/events
model.observer.source.component=inesdata-connector:model-observer-dsp-events